apiVersion: v2
name: unified-observability-stack
description: >
  Umbrella Helm chart to deploy and manage observability components
  such as Grafana, Loki, Tempo, Thanos, and MinIO.
type: application
version: 0.2.0
appVersion: "1.0.0"

dependencies:
  - name: grafana
    version: 10.3.1
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled

  - name: loki
    version: 6.49.0
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled

  - name: tempo
    version: 1.24.1
    repository: https://grafana.github.io/helm-charts
    condition: tempo.enabled

  - name: thanos
    version: 0.10.0
    repository: oci://ghcr.io/solidcharts/helm-charts/thanos
    condition: thanos.enabled

  - name: rustfs
    version: 0.0.73
    repository: https://charts.rustfs.io
    condition: rustfs.enabled
